### ISSUE TITLE
Source tarball missing protocol.h

### ISSUE THREAD

**Issue by tdm4** [QW-Group/mvdsv#120]
Hi,

   Please consider adding protocol.h back into the source tarball (checking it back into the mvdsv repo). Github's generated source tarballs do not include git submodules.  The OpenBSD ports system relies on a .tgz of the source to compile it properly, and https://github.com/QW-Group/mvdsv/archive/refs/tags/0.36.tar.gz is missing this file.

  Pull request #114 was when protocol.h was removed from the main repo.

   Thanks!

**Comment by VVD** [comment]
I said this already multiple times to developers, but they ignore or don't know how to do this…
Probably OpenBSD need #111 too.

**Comment by dsvensson** [comment]
One "workaround" to somewhat more clearly announce that the auto-generated source zip from GitHub should not be used is to make it empty:

https://stackoverflow.com/questions/45240336/how-to-use-github-release-api-to-make-a-release-without-source-code/58443948#58443948

Unfortunately it's not possible to disable the zip file.

**Comment by VVD** [comment]
Me and @tdm4 ask about release: https://github.com/QW-Group/mvdsv/releases/tag/0.36
Can you create release tarballs self with all necessary files?

**Comment by VVD** [comment]
Something like this: https://sourceforge.net/projects/mvdsv/files/MVDSV/

**Comment by tcsabina** [comment]
Hi Tom,

protocol.h was moved to a repository that is shared among many QW related projects, mainly ezquake and mvdsv. The reason behind this was to avoid copy+pasting changes of the same file among many projects, and to have a version controlled protocol extensions, which seems to be quite active nowdays (thanks to nano and the mapping community). So I am afraid that rollback is not really an option.

These tarballs are auto-generated upon release. Quite stupid form github not to include all the submodule files, but who am I to judge ;). So far I have never paid attention to these files, but if you are relying on these, I can make sure that upon a new release, all the necessary files are in there (with manually creating the .zip and the .tar.gz files). Would this work for you?

**Comment by qqshka** [comment]
meanwhile, you can download tgz for particular commit for mvdsv and qwprot and combine source code

```
curl -v -L -O -J https://api.github.com/repos/QW-Group/mvdsv/tarball/971e7de49255fb41d56ae8e9332825bbf15617a8
curl -v -L -O -J https://api.github.com/repos/QW-Group/qwprot/tarball/53af547d0608a1507895fc1629cdc3f4820fc0af

```

**Comment by tdm4** [comment]
Closing this out. There is a new feature in OpenBSD ports called `DIST_TUPLE` which allows me to pull down git submodules, so I've rewritten the port's Makefile to suit. I've tested it and it makes a successful package for me on OpenBSD.

Thanks!
