### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by lockheed** [QW-Group/mvdsv#137]
Does this have docker container? Is it possible to run this in docker?

**Comment by ciscon** [comment]
someone wrote some docker stuff for it at some point and i think i even corrected some of it in a fork that's probably long gone (i think it was this https://github.com/niclaslindstedt/nquakesv-docker)
it's certainly possible to run it in docker though most servers are being run on vms in the cloud in which case it's just as simple to run the nquakesv installer script outside of a container.

**Comment by lockheed** [comment]
Thanks for responding. 
I am already using this fork for docker: https://github.com/frehall/qwserver-docker , which seems to be the latest (it even includes docker-compose, on which I am basing mine) and it is working fine, with one strange exception: if I change server port to anything else than 27500 (e.g. 27501), the server no longer appears on the list of master servers, even tough it regularly sends them a heartbeat.

I can't figure out why, because it is live and I can connect to it.

**Comment by ciscon** [comment]
i'm sure it's a bug in the docker image it's referencing for mvdsv, you might want to create your own using their dockerfile and reference that instead so you can fix it, i'm sure it's some tiny bug.

**Comment by lockheed** [comment]
I tried building it with supplied Dockerfile but I can't get it to build: https://pastebin.com/raw/GmrQ88JG

Even if I replace ubuntu:18.04 with debian:stable-slim, I get the same issue.

**Comment by tcsabina** [comment]
Hi @lockheed,
You will get more support with this issue in the QW discord. Check the 'Acknowledgments' part of the main page on the repo...

**Comment by lockheed** [comment]
It turns out the servers do appear in masterlist, but it takes some of them about 12 hours to do so. Strange, considering they are all on the same server and run with same commands and others appear within minutes.
