### ISSUE TITLE
Server-side weapon switching not always hiding weapon when cl_weaponhide set

### ISSUE THREAD

**Issue by ciscon** [QW-Group/mvdsv#57]
With a decent ping, using +fire and having cl_weaponhide 1, quickly pressing the +fire bind will result in the weapon fired being kept out, as opposed to when manually configuring serverside weapons, eg

cmd wreg a +75234
cmd wreg z -1
alias +rl "cmd a;set lastattack rl;setinfo w_rank 75234"
alias -rl "if ($lastattack == 'rl') then cmd z"

**Comment by meag** [comment]
Hi ciscon

Can you please provide:

`deatchmatch` mode of the server you were playing on
values of:
- `cl_weaponpreselect`
- `cl_weaponhide`
- `cl_weaponhide_axe`
- `cl_weaponforgetorder`
- `cl_weaponforgetondeath`

Thanks,
meag

**Comment by ciscon** [comment]
all default and
cl_weaponhide                         "1"
cl_weaponpreselect                    "1"

**Comment by tcsabina** [comment]
Server side weapon switching was a tryout, but it had some issues without solutions, so it was stopped my meag.
closing
